---
title: "Exemplo -  Curva padrão"
---

```{r setup}
library(pacman)
p_load(readr, dplyr, ggplot2, ggpmisc, broom, purrr, tidyr)
```

```{r}
padrao <- read_csv2("dados/absorbancia_padrao.csv")

padrao
```

```{r}
leitura <- read_csv2("dados/absorbancia_leitura.csv")

leitura
```

```{r}
ggplot(padrao, aes(absorbancia, concentracao)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~~")), formula = y ~ x, parse = TRUE) +
  facet_wrap(~grupo)
```

```{r}
grupo1 <- lm(concentracao ~ absorbancia, data = filter(padrao, grupo == 1))
```

```{r}
glance(grupo1)
```

```{r}
tidy(grupo1)
```

```{r}
grupo2 <- lm(concentracao ~ absorbancia, data = filter(padrao, grupo == 2))
```

```{r}
glance(grupo2)
```

```{r}
tidy(grupo2)
```


```{r}
grupos <- padrao %>%
  group_by(grupo) %>%
  do(ajuste = lm(concentracao ~ absorbancia, data = .))
 
grupos
```
```{r}
grupos %>% glance(ajuste)
```

```{r}
grupos %>% tidy(ajuste)
```
```{r}
grupos %>% augment(ajuste, newdata = leitura)
```

